apiVersion: v1
kind: Service
metadata:
  name: v-sepp
  namespace: open5gs
spec:
  type: ClusterIP
  selector:
    app: v-sepp
  ports:
  - name: sbi
    protocol: TCP
    port: 80
    targetPort: 80
  - name: n32c
    protocol: TCP
    port: 7778
    targetPort: 7778
  - name: n32f
    protocol: TCP
    port: 7779
    targetPort: 7779