apiVersion: v1
kind: ConfigMap
metadata:
  name: v-smf-config
  namespace: open5gs
data:
  smf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/smf.log

    global:

    smf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 80
        client:
          nrf:
            - uri: http://v-nrf.open5gs.svc.cluster.local:80
      pfcp:
        server:
          - address: 0.0.0.0
            port: 8805
        client:
          upf:
            - address: v-upf.open5gs.svc.cluster.local
              port: 8805
      gtpu:
        server:
          - address: 0.0.0.0
      session:
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1
      dns:
        - 8.8.8.8
        - 8.8.4.4
      mtu: 1400 