apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-smf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v-smf
  template:
    metadata:
      labels:
        app: v-smf
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name": "pfcp-network",
              "interface": "pfcp",
              "ips": ["192.168.10.102/24"]
            },
            {
              "name": "gtpu-network",
              "interface": "gtpu",
              "ips": ["192.168.20.102/24"]
            }
          ]
    spec:
      containers:
        - name: v-smf
          image: docker.io/library/smf:v2.7.5
          imagePullPolicy: IfNotPresent
          command: [ "open5gs-smfd", "-c", "/etc/open5gs/smf.yaml" ]
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/smf.yaml
              subPath: smf.yaml
          ports:
            - containerPort: 80
              name: sbi
              protocol: TCP
            - containerPort: 8805
              name: pfcp
              protocol: UDP
      volumes:
        - name: config
          configMap:
            name: v-smf-config