apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-smf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v-smf
  template:
    metadata:
      labels:
        app: v-smf
    spec:
      containers:
        - name: v-smf
          image: docker.io/library/smf:v2.7.5
          imagePullPolicy: IfNotPresent
          command: [ "open5gs-smfd", "-c", "/etc/open5gs/smf.yaml", "-a", "v-smf.open5gs.svc.cluster.local" ]
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/smf.yaml
              subPath: smf.yaml
          ports:
            - containerPort: 80
              name: sbi
      volumes:
        - name: config
          configMap:
            name: v-smf-config 