apiVersion: v1
kind: Service
metadata:
  name: v-smf
  namespace: open5gs
spec:
  selector:
    app: v-smf
  ports:
    - name: sbi
      protocol: TCP
      port: 80
      targetPort: sbi 
    - name: pfcp
      protocol: UDP
      port: 8805
      targetPort: pfcp

