apiVersion: v1
kind: ConfigMap
metadata:
  name: v-upf-config
  namespace: open5gs
data:
  upf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/upf.log
      level: trace

    global:

    upf:
      pfcp:
        server:
          - address: 192.168.10.101
            port: 8805
      gtpu:
        server:
          - address: 192.168.20.101
      session:
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1