apiVersion: v1
kind: ConfigMap
metadata:
  name: v-upf-config
  namespace: open5gs
data:
  upf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/upf.log
      level: debug

    global:

    upf:
      pfcp:
        server:
          - address: $(POD_IP_PFCP)  # This will be replaced with the IP from Multus pfcp interface
            port: 8805
        client:
      gtpu:
        server:
          - address: $(POD_IP_GTPU)  # This will be replaced with the IP from Multus gtpu interface
      session:
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1