apiVersion: v1
kind: ConfigMap
metadata:
  name: v-upf-config
  namespace: open5gs
data:
  upf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/upf.log

    global:

    upf:
      pfcp:
        server:
          - address: 0.0.0.0
            port: 8805
        client:
      gtpu:
        server:
          - address: 0.0.0.0
      session:
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1