apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-upf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v-upf
  template:
    metadata:
      labels:
        app: v-upf
    spec:
      containers:
        - name: v-upf
          image: docker.io/library/upf:v2.7.5
          imagePullPolicy: IfNotPresent 
          command: [ "open5gs-upfd", "-c", "/etc/open5gs/upf.yaml" ]
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/upf.yaml
              subPath: upf.yaml
            - name: dev-net-tun
              mountPath: /dev/net/tun
              readOnly: true
          ports:
            - name: pfcp
              containerPort: 8805
              protocol: UDP
            - name: gtpu
              containerPort: 2152
              protocol: UDP
      volumes:
        - name: config
          configMap:
            name: v-upf-config
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice