apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-upf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v-upf
  template:
    metadata:
      labels:
        app: v-upf
    spec:
      containers:
        - name: v-upf
          image: open5gs-v-upf:latest
          command: [ "open5gs-upfd", "-c", "/etc/open5gs/upf.yaml" ]
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/upf.yaml
              subPath: upf.yaml
          ports:
            - containerPort: 80
              name: sbi
      volumes:
        - name: config
          configMap:
            name: v-upf-config 