apiVersion: v1
kind: Service
metadata:
  name: v-upf
  namespace: open5gs
spec:
  type: ClusterIP
  selector:
    app: v-upf
  ports:
  - name: pfcp
    protocol: UDP
    port: 8805
    targetPort: 8805
  - name: gtpu
    protocol: UDP
    port: 2152
    targetPort: 2152
