apiVersion: apps/v1
kind: Deployment
metadata:
  name: h-nrf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: h-nrf
  template:
    metadata:
      labels:
        app: h-nrf
    spec:
      containers:
        - name: h-nrf
          image: docker.io/library/nrf:v2.7.5
          imagePullPolicy: IfNotPresent
          command: [ "open5gs-nrfd", "-c", "/etc/open5gs/nrf.yaml", "-a", "h-nrf.open5gs.svc.cluster.local" ]
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/nrf.yaml
              subPath: nrf.yaml
          ports:
            - containerPort: 80
              name: http
      volumes:
        - name: config
          configMap:
            name: h-nrf-config
