apiVersion: apps/v1
kind: Deployment
metadata:
  name: packetrusher
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: packetrusher
  template:
    metadata:
      labels:
        app: packetrusher
    spec:
      containers:
        - name: packetrusher
          image: ghcr.io/borjis131/packetrusher:20250225
          imagePullPolicy: IfNotPresent
          command: ["/PacketRusher/packetrusher"]
          args: ["--config", "/PacketRusher/config/packetrusher.yaml", "ue"]
          securityContext:
            privileged: true
            capabilities:
              add: ["ALL", "NET_ADMIN"]
          volumeMounts:
            - name: config
              mountPath: /PacketRusher/config/packetrusher.yaml
              subPath: packetrusher.yaml
      volumes:
        - name: config
          configMap:
            name: packetrusher-config
