# First, define the Persistent Volume Claims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: h-sepp-certs
  namespace: open5gs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: h-sepp-ca
  namespace: open5gs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
# Then, define the Deployment with updated configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: h-sepp
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: h-sepp
  template:
    metadata:
      labels:
        app: h-sepp
    spec:
      containers:
        - name: h-sepp
          image: docker.io/library/sepp:v2.7.5
          imagePullPolicy: IfNotPresent
          command: ["/entrypoint.sh"]  # Use the entrypoint script
          args: ["-c", "/etc/open5gs/sepp.yaml"]
          env:
            - name: SEPP_TYPE
              value: "sepp1"
            - name: REGENERATE_CERTS
              value: "true"
            - name: TLS_DIR
              value: "/etc/open5gs/default/tls"
            - name: SEPP_FQDN
              value: "h-sepp.open5gs.svc.cluster.local"
            - name: SEPP_PLMN_FQDN
              value: "sepp.5gc.mnc001.mcc001.3gppnetwork.org"
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/sepp.yaml
              subPath: sepp.yaml
            - name: certs
              mountPath: /etc/open5gs/default/tls
            - name: ca
              mountPath: /etc/open5gs/default/ca
            - name: logs
              mountPath: /var/log/open5gs
          ports:
            - containerPort: 80
              name: http
            - containerPort: 7778
              name: n32c
            - containerPort: 7779
              name: n32f
      volumes:
        - name: config
          configMap:
            name: h-sepp-config
        - name: certs
          emptyDir: {}  # Use emptyDir instead of PVC
        - name: ca
          emptyDir: {}  # Use emptyDir instead of PVC
        - name: logs
          emptyDir: {}