apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-amf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v-amf
  template:
    metadata:
      labels:
        app: v-amf
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name": "ngap-network",
              "interface": "ngap",
              "ips": ["192.168.30.101/24"]
            }
          ]
    spec:
      containers:
        - name: v-amf
          image: docker.io/library/amf:v2.7.5
          imagePullPolicy: IfNotPresent
          command: [ "open5gs-amfd", "-c", "/etc/open5gs/amf.yaml" ]
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/amf.yaml
              subPath: amf.yaml
          ports:
            - containerPort: 80
              name: sbi
            - containerPort: 38412
              name: ngap
      volumes:
        - name: config
          configMap:
            name: v-amf-config