apiVersion: v1
kind: Service
metadata:
  name: v-amf
  namespace: open5gs
spec:
  selector:
    app: v-amf
  ports:
    - name: sbi
      protocol: TCP
      port: 80
      targetPort: sbi
    - name: ngap
      protocol: UDP
      port: 38412
      targetPort: ngap
