apiVersion: v1
kind: Service
metadata:
  name: v-amf
  namespace: open5gs
spec:
  type: ClusterIP
  selector:
    app: v-amf
  ports:
    - name: sbi
      port: 80
      targetPort: 80
      protocol: TCP
    - name: ngap
      port: 38412
      targetPort: 38412
      protocol: SCTP 
