apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-bsf
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v-bsf
  template:
    metadata:
      labels:
        app: v-bsf
    spec:
      containers:
        - name: v-bsf
          image: docker.io/library/bsf:v2.7.5
          imagePullPolicy: IfNotPresent
          command: [ "open5gs-bsfd", "-c", "/etc/open5gs/bsf.yaml", "-a", "v-bsf.open5gs.svc.cluster.local" ]
          volumeMounts:
            - name: config
              mountPath: /etc/open5gs/bsf.yaml
              subPath: bsf.yaml
          ports:
            - containerPort: 80
              name: sbi
      volumes:
        - name: config
          configMap:
            name: v-bsf-config 