apiVersion: apps/v1
kind: Deployment
metadata:
  name: packetrusher
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: packetrusher
  template:
    metadata:
      labels:
        app: packetrusher
    spec:
      containers:
        - name: packetrusher
          image: your-registry/packetrusher:latest  # Replace with your image
          imagePullPolicy: IfNotPresent
          workingDir: /PacketRusher
          command: [ "./packetrusher", "ue" ]
          volumeMounts:
            - name: config
              mountPath: /PacketRusher/config/config.yml
              subPath: config.yml
          securityContext:
            privileged: true
      volumes:
        - name: config
          configMap:
            name: packetrusher-config
