apiVersion: apps/v1
kind: Deployment
metadata:
  name: packetrusher
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: packetrusher
  template:
    metadata:
      labels:
        app: packetrusher
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            {
              "name": "ngap-network",
              "interface": "ngap",
              "ips": ["192.168.30.102/24"]
            },
            {
              "name": "gtpu-network",
              "interface": "gtpu",
              "ips": ["192.168.20.103/24"]
            }
          ]
    spec:
      containers:
        - name: packetrusher
          image: ghcr.io/borjis131/packetrusher:20250225
          imagePullPolicy: IfNotPresent
          workingDir: /PacketRusher
          command: [ "./packetrusher", "ue" ]
          volumeMounts:
            - name: config
              mountPath: /PacketRusher/config/config.yml
              subPath: config.yml
          ports:
            - containerPort: 38412
              name: ngap
              protocol: UDP
            - containerPort: 2152
              name: gtpu
              protocol: UDP
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
      volumes:
        - name: config
          configMap:
            name: packetrusher-config