apiVersion: apps/v1
kind: Deployment
metadata:
  name: packetrusher
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: packetrusher
  template:
    metadata:
      labels:
        app: packetrusher
    spec:
      containers:
        - name: packetrusher
          image: ghcr.io/borjis131/packetrusher:20250225
          args: [ "--config", "/PacketRusher/config/packetrusher.yaml", "ue" ]
          volumeMounts:
            - name: config
              mountPath: /PacketRusher/config/packetrusher.yaml
              subPath: packetrusher.yaml
          ports:
            - containerPort: 38412
              name: ngap
            - containerPort: 2152
              name: gtpu
          securityContext:
            privileged: true
            capabilities:
              add: [ "NET_ADMIN", "ALL" ]
      volumes:
        - name: config
          configMap:
            name: packetrusher-config
