apiVersion: v1
kind: Service
metadata:
  name: packetrusher
  namespace: open5gs
spec:
  type: ClusterIP
  selector:
    app: packetrusher
  ports:
    - name: ngap
      protocol: UDP
      port: 38412
      targetPort: ngap
    - name: gtpu
      protocol: UDP
      port: 2152
      targetPort: gtpu
