apiVersion: v1
kind: ConfigMap
metadata:
  name: h-ausf-config
  namespace: open5gs
data:
  ausf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/ausf.log

    global:

    ausf:
      sbi:
        server:
          - address: ausf.5gc.mnc001.mcc001.3gppnetwork.org
            port: 80
        client:
          nrf:
            - uri: http://nrf.5gc.mnc001.mcc001.3gppnetwork.org:80
