apiVersion: v1
kind: ConfigMap
metadata:
  name: v-ausf-config
  namespace: open5gs
data:
  ausf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/ausf.log

    global:

    ausf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 80
        advertise:
          - address: v-ausf.open5gs.svc.cluster.local
            port: 80
        client:
          nrf:
            - uri: http://v-nrf.open5gs.svc.cluster.local:80
