apiVersion: v1
kind: Service
metadata:
  name: v-ausf
  namespace: open5gs
spec:
  type: ClusterIP
  selector:
    app: v-ausf
  ports:
    - name: sbi
      protocol: TCP
      port: 80
      targetPort: sbi
