apiVersion: v1
kind: ConfigMap
metadata:
  name: h-udm-config
  namespace: open5gs
data:
  udm.yaml: |
    logger:
      file:
        path: /var/log/open5gs/udm.log

    global:

    udm:
      sbi:
        server:
          - address: udm.5gc.mnc001.mcc001.3gppnetwork.org
            port: 80
        client:
          nrf:
            - uri: http://nrf.5gc.mnc001.mcc001.3gppnetwork.org:80
